name: "🚀 Feature Suggestion"
description: "Suggest a new feature or improvement for TLBAS."
title: "[FEATURE] ${{ summary }}"
labels:
  - enhancement
  - needs triage
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        <!-- Thank you for suggesting a new feature! Please describe your idea in detail. -->

  - type: checkboxes
    id: preliminary-checks
    attributes:
      label: "**Preliminary Checks**"
      options:
        - label: "I have searched the existing [issues](https://github.com/Vadim-Khristenko/tlbas/issues) and this feature request hasn't been suggested yet."

  - type: input
    id: summary
    attributes:
      label: "Short and clear summary"
      description: "Provide a brief summary of the feature."
      placeholder: "e.g. Support custom themes"
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "💡 Problem Statement / Motivation"
      description: "Describe the problem or limitation you’re facing."
      placeholder: "e.g. It is not possible to customize UI colors without core changes."
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: "🚀 Proposed Solution"
      description: "Detail how the new feature should work."
      placeholder: "e.g. Add a `--theme` flag that loads a custom CSS file."
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "✅ Acceptance Criteria (Optional)"
      description: "Define how we will know this feature is complete."
      placeholder: "- Users can pass `--theme` to the CLI\n- Theme CSS is applied correctly"
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: "🔄 Alternatives Considered (Optional)"
      description: "Describe any alternative solutions you considered."
      placeholder: "e.g. Using environment variables, but they don't cover all use cases."
      required: false

  - type: textarea
    id: drawbacks
    attributes:
      label: "⚖️ Potential Drawbacks (Optional)"
      description: "List any trade‑offs or downsides."
      placeholder: "e.g. Increased complexity in the configuration loader."
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: "📚 Additional Context (Optional)"
      description: "Add any other context, mockups, or links."
      placeholder: "Screenshots, examples, or related discussions."
      required: false